import { Transaction, User } from "@/types/transaction";

export const formatNaira = (amount: number): string => {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    minimumFractionDigits: 0,
  }).format(amount);
};

export const users: User[] = [
  {
    id: "buyer-1",
    name: "Tunde",
    location: "London, UK",
    role: "buyer",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tunde",
  },
  {
    id: "seller-1",
    name: "Mama Bose",
    location: "Balogun, Lagos",
    role: "seller",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bose",
  },
  {
    id: "agent-1",
    name: "Agent Chidi",
    location: "Back Office",
    role: "agent",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=chidi",
  },
];

export const transactions: Transaction[] = [
  {
    id: "TM-2847",
    buyerId: "buyer-1",
    sellerId: "seller-1",
    itemName: "Ankara Lace Fabric",
    itemDescription: "High-quality Ankara lace, 6 yards",
    itemPrice: 150000,
    deliveryFee: 25000,
    totalAmount: 175000,
    status: "pending_payment",
    buyerName: "Tunde",
    sellerName: "Mama Bose",
    location: "Balogun, Lagos",
    itemImage: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop",
    createdAt: new Date("2024-01-15T10:00:00"),
    updatedAt: new Date("2024-01-15T10:00:00"),
    paymentReference: "TM-2847",
    escrowLocked: false,
    logisticsConfirmed: false,
    deliveryPhoto: null,
    buyerConfirmed: false,
    disputeFlagged: false,
  },
  {
    id: "TM-2848",
    buyerId: "buyer-1",
    sellerId: "seller-1",
    itemName: "Pure Water Pack",
    itemDescription: "Bulk pure water, 24 bottles",
    itemPrice: 80000,
    deliveryFee: 15000,
    totalAmount: 95000,
    status: "payment_confirmed",
    buyerName: "Tunde",
    sellerName: "Mama Bose",
    location: "Bodija, Ibadan",
    itemImage: "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=400&h=400&fit=crop",
    createdAt: new Date("2024-01-14T14:30:00"),
    updatedAt: new Date("2024-01-15T09:00:00"),
    paymentReference: "TM-2848",
    escrowLocked: true,
    logisticsConfirmed: false,
    deliveryPhoto: null,
    buyerConfirmed: false,
    disputeFlagged: false,
  },
  {
    id: "TM-2849",
    buyerId: "buyer-1",
    sellerId: "seller-1",
    itemName: "Used Electronics",
    itemDescription: "Laptop and phone accessories",
    itemPrice: 200000,
    deliveryFee: 30000,
    totalAmount: 230000,
    status: "in_transit",
    buyerName: "Tunde",
    sellerName: "Mama Bose",
    location: "Balogun, Lagos",
    itemImage: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
    createdAt: new Date("2024-01-13T08:00:00"),
    updatedAt: new Date("2024-01-15T11:00:00"),
    paymentReference: "TM-2849",
    escrowLocked: true,
    logisticsConfirmed: true,
    deliveryPhoto: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400&h=400&fit=crop",
    buyerConfirmed: false,
    disputeFlagged: false,
  },
  {
    id: "TM-2850",
    buyerId: "buyer-1",
    sellerId: "seller-1",
    itemName: "Fabric Bundle",
    itemDescription: "Mixed fabric for dressmaking",
    itemPrice: 120000,
    deliveryFee: 20000,
    totalAmount: 140000,
    status: "delivered",
    buyerName: "Tunde",
    sellerName: "Mama Bose",
    location: "Bodija, Ibadan",
    itemImage: "https://images.unsplash.com/photo-1544441893-675973e31985?w=400&h=400&fit=crop",
    createdAt: new Date("2024-01-10T12:00:00"),
    updatedAt: new Date("2024-01-14T16:00:00"),
    paymentReference: "TM-2850",
    escrowLocked: true,
    logisticsConfirmed: true,
    deliveryPhoto: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400&h=400&fit=crop",
    buyerConfirmed: true,
    disputeFlagged: false,
  },
];

export const statusLabels: Record<Transaction["status"], string> = {
  pending_payment: "Pending Payment",
  payment_confirmed: "Payment Confirmed",
  in_transit: "In Transit",
  delivered: "Delivered",
};

export const statusColors: Record<Transaction["status"], string> = {
  pending_payment: "bg-yellow-100 text-yellow-800",
  payment_confirmed: "bg-blue-100 text-blue-800",
  in_transit: "bg-purple-100 text-purple-800",
  delivered: "bg-green-100 text-green-800",
};
